# Generated by Django 2.2.3 on 2020-06-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('poster_id', models.CharField(max_length=16)),
                ('post_date', models.DateTimeField(verbose_name='date posted')),
            ],
        ),
    ]
