# Generated by Django 2.2.3 on 2020-06-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('passhash', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='poster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bc_chat.User'),
        ),
    ]
